version: '3.8'

services:
  db:
    container_name: events-postgres
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:5432
